import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
export default function Home() {
  return (
    <div className={styles.main_page}>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://vk.com/may_d">MARINA land!</a>
        </h1>

        <div className={styles.grid}>
          <Link href="/dersiption">
          <a  className={styles.card}>
            
            <h2>Почему Я люблю МАРИНУ? &rarr;</h2>
            <p>Нажми и узнаешь</p>
          </a>
          </Link>
         
        </div>
      </main>

      
    </div>
    </div>
  )
}
